Vote feature
timTonelli/coffee-code pull request #14
Opened 2022-05-11 17:36 UTC by timTonelli

- Set up migration to create votes table
- Set up model for objection to pull records as Vote objects
- Set up seeder for votes
- Create React component for vote section of reviews, including buttons, show the sum of votes, and managing state to properly show the user up to date vote info
- Set up back end routes to handle get, post and patch requests regarding votes for each review
- Create helper function to help server send pertinent info to keep track of necessary state
- Set up basic styling to properly represent if user has upvoted/downvoted

2022-05-11 17:52 UTC, nwalberts requested changes

2022-05-11 17:52 UTC, nwalberts commented on client/src/assets/scss/main.scss
> +
i think we can remove htis

2022-05-11 17:52 UTC, nwalberts commented on client/src/assets/scss/main.scss
> +
remove extra lines

2022-05-11 17:52 UTC, nwalberts commented on client/src/components/CoffeeShopShowPage.js
> +    return <ReviewTile key={review.id} {...review} coffeeShopId={coffeeShop.id}  />
you shouldnt need the id of the coffee shop in props

2022-05-11 17:52 UTC, nwalberts commented on client/src/components/ReviewTile.js
> +      const response = await fetch(`/api/v1/coffee-shops/${coffeeShopId}/reviews/${id}/votes`)
this is a _deeply nested route_, which generally we want to avoid. 

You dont need the coffeeShopId on the backend for any reason. You just need the review id.

Please update this fetch request to not have the coffeeShopId, and similarly update your backend to not expect it

2022-05-11 17:52 UTC, nwalberts commented on client/src/components/ReviewTile.js
> +      const response = await fetch(`/api/v1/coffee-shops/${coffeeShopId}/reviews/${id}/votes`, {
same thing as above, we dont need the coffee shop id

2022-05-11 17:52 UTC, nwalberts commented on client/src/components/ReviewTile.js
> +      const response = await fetch(`/api/v1/coffee-shops/${coffeeShopId}/reviews/${id}/votes`)
wait a second....hold up. This is no beuno. All of this information should have been gotten in your initial show page get request. 

update your coffeeshopshow component to retrieve all of the votes _along side the coffee shop and reviews information_. There should not be a get request on useEffect (otherwise we will have TONS of fetch requests and database queries)

2022-05-11 17:52 UTC, nwalberts commented on client/src/components/ReviewTile.js
> +  }, [])
remove per above comment

2022-05-11 17:52 UTC, nwalberts commented on client/src/components/ReviewTile.js
> +    }
this is fine, but its also okay if we dont know if a vote has been made by a user for the review. You can just have one endpoint (likely a post endpoint) handle both updates and creation of new votes. 

Think of HTTP verbs as a guideline, not a rule :P 

This would also mean you wouldnt need to track if the vote already exists in state

2022-05-11 17:52 UTC, nwalberts commented on client/src/components/ReviewTile.js
> +      console.log(body)
remove console.log

2022-05-11 17:52 UTC, nwalberts commented on client/src/components/VotesSection.js
> +      {/* <label htmlFor="upvote" /> */}
remove if unused

2022-05-11 17:52 UTC, nwalberts commented on server/src/models/Vote.js
> +        vote: { type: ["string", "integer"] }
I know this will be frustrating to update, but we shouldnt have a property of "Vote" be "vote". its ambiguous and can lead human engineers to errors. Update this to something like "value" or "status"

2022-05-11 17:52 UTC, nwalberts commented on server/src/routes/api/v1/reviewVotesRouter.js
> +})
this entire endpoint will be deleted. You will get existing routes in your coffeeShopsRouter "show" endpoint. You'll need to update your existing CofeeShopSerializer

2022-05-11 17:52 UTC, nwalberts commented on server/src/routes/api/v1/reviewVotesRouter.js
> +  console.log("HEY YOU'RE POSTING")
delete

2022-05-12 17:54 UTC, timTonelli commented
Ohad gave us feedback that the `updateVoteData` function in our Review Tile component should be moved out to a separate file as a service function, but when we did that it severely hindered performance, so we left it as is. Let us know if that works, or if we should change it.

2022-05-12 20:36 UTC, merged